stock_bot:
  container_name: stock_bot

  image: cocasema/stock_bot

  hostname: stock_bot
  domainname: foobar.com

  mem_limit: 128m
  memswap_limit: 128m

  restart: always

  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /data/stock_bot:/etc/stock_bot

stock_bot_test:
  extends:
    service: stock_bot
  environment:
   - TEST=1